config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'products/:id' => 'products#show', as: :show_product
  root "pages#home"
  get '/about', to:'pages#about'
  resources :todos
  resources :products
  resources :pages
  resources :recipes do 
    resources :comments, only: [:create]
  end
  resources :ingredients, except: [:destroy]
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #config real--time
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  resources :messages, only:[:create]
end

app/models/product.rb
class Product < ApplicationRecord
  extend Enumerize
  enumerize :level, in: { easy: 1, medium: 2, hard: 3 }
  
  validates :title, :description, presence: true
  validate :title_is_shorter_than_description
  validates :price, presence: true, numericality: { greater_than: 0 }
  
  belongs_to :category, optional: true
  
  before_save :strip_html_from_description
  before_save :set_title_to_lower_case
  
  scope :published, -> { where(published: true) }
  scope :priced_more_than, ->(price) { where('price > ?', price) }

  def title_is_shorter_than_description
    return if title.blank? or description.blank?
    if description.length < title.length
      errors.add(:description, 'can\'t be shorter than title')
    end
  end
  
  def strip_html_from_description
    self.description = ActionView::Base.full_sanitizer.sanitize(self.description)
  end
 
  def set_title_to_lower_case
    self.title = self.title.downcase
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:update, :show, :edit, :destroy]
  def index
    @products = Product.where(published: nil)
  end

  def show
    #@product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.all
  end
  
  def create
    @product = Product.new(product_params)
    @categories = Category.all
    # if @product.save
    #   # redirect_to products_url
    #   flash[:notice] = 'successfully'
    #   redirect_to products_url

    # else 
    #   flash.now[:notice] = 'Error'
    #   render :new 
    # end
    return redirect_to products_url, notice: 'you have successfully create product' if @product.save
    flash.now[:notice] = 'There is an error in your form'
    render :new
  end

  def edit
    # @product = Product.find(params[:id])
    render :new
  end

  def update
    #@product = Product.find(params[:id])
    return redirect_to products_url, notice: 'you have successfully update product' if @product.update(product_params)
    flash.now[:notice] = 'There is an error in your update form'
    render :new
  end

  def destroy
    return redirect_to products_url, notice: 'you have successfully delete product' if @product.destroy
    flash.now[:notice] = 'There is an error in your delete form'
    render :new
  end 

  private

  def product_params
    product_params = params.require(:product).permit( :title, :description, :price, :published, :category_id, :country)
  end

  def get_product
    @product = Product.find(params[:id])
  end
end

app/views/products/_product.html.slim
<%= product.title %>
<%= product.description %>
<%= product.price %>

app/views/products/index.html.slim
table
	- @products.each do |product|
		tr.products
			td = product.title
			td = product.price
			td = product.category.try(:name)
			td = product.price
			td = link_to('Read more', product_path(product))
			td = link_to('Edit',edit_product_path(product))
			td = link_to('Delete', product_path(product),method: :delete, data: { confirm: 'are you sure to delete this product?'})
= link_to('create',new_product_path)

app/views/products/new.html.slim
.container
  = simple_form_for @product do |f|
    = f.input :title
    = f.input :description
    = f.input :price, min: 0
    = f.association :category
    = f.input :country
    = f.button :submit

app/views/products/show.html.slim
h1
  | Title: #{@product.title}
h1
  | Description: #{@product.description}
h1
  | Price: #{@product.price}
h1
  | Level: #{@product.level}
h1
  | Published: #{@product.published}
h1
  | Country: #{@product.country}